### ISSUE TITLE
Unexpected error occurred on starting Session Native

### ISSUE THREAD

**Issue by BenK885** [VityaSchel/session-native#3]
Session Native says:
"Unexpected error occured
Session Native can't connect to the Bun backend via unix socket. Please create an issue on GitHub specifying as much details about your OS, environment and actions that led to this error as possible."

<img width="895" alt="Bildschirmfoto 2024-09-25 um 15 15 25" src="https://github.com/user-attachments/assets/4b1d5888-8967-4bf4-a605-d6947bb54ae7">

Konsole says:
"Failed to run sidecar binary: Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted""

My System:
Apple Mac mini M1, 2020 / 16 GB Ram / macOS Sequoia 15.0

[Console - Session Native process.txt](https://github.com/user-attachments/files/17131620/Console.-.Session.Native.process.txt)

**Comment by VityaSchel** [comment]
Hi, thank you for reporting that issue, can you try dragging /path/to/Session\ Native.app/Contents/Resources/backend binary to your terminal, running it and see what happens?

**Comment by BenK885** [comment]
Terminal says:
```
❯ xattr -d com.apple.quarantine Session\ Native.app/
❯ /Applications/Messenger/Session\ Native.app/Contents/Resources/backend
Server listening on /Users/ben/Library/Containers/dev.hloth.Session-Native/Data/tmp/bun_socket
```

With that terminal in the background, I can now start and run the Session Native app.

<img width="919" alt="Bildschirmfoto 2024-09-25 um 15 28 44" src="https://github.com/user-attachments/assets/d763c981-bc7e-4e58-8905-e3f2a8889011">

**Comment by VityaSchel** [comment]
I wonder why Swift can't run the binary though 🤔 Could be some sandboxing restrictions by os
But glad you got it somehow working

**Comment by johnstef99** [comment]
Event after that I get this error message in the backend
```
ENOENT: No such file or directory
   errno: -2
 syscall: "open"
   path: "/Users/hloth/Library/Containers/dev.hloth.Session-Native/Data/tmp/session_data_4164826294262965133"

      at new I5 (/$bunfs/root/darwin_arm:146:357310)
      at /$bunfs/root/darwin_arm:146:358461
      at Ag (/$bunfs/root/darwin_arm:146:358763)
      at /$bunfs/root/darwin_arm:146:358310
      at D7 (/$bunfs/root/darwin_arm:146:358364)
```
it seems there is a hardcoded path, maybe swift tries to run the backend and gets the exact same error?

**Comment by johnstef99** [comment]
I think i found out what is going on, you have compiled the backend with bun to be one executable but in the compile step the HOME variable is getting resolved to your HOME.

**Comment by VityaSchel** [comment]
> I think i found out what is going on, you have compiled the backend with bun to be one executable but in the compile step the HOME variable is getting resolved to your HOME.

Well I tried to fix this but bun kept inlining all env variables during compilation step :D
Then, it seems I finally tricked the compiler so I've decided to publish the app

**Comment by VityaSchel** [comment]
It keeps happening, presumably because when Swift spawns Process() it does not set HOME env variable

**Comment by VityaSchel** [comment]
I fixed it by passing home directory in argument instead of env variable. You can download new version here: https://github.com/VityaSchel/session-native/releases/tag/v1.0.0
